name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --repo ${{ github.repository }} "${GITHUB_REF#refs/tags/}"
  build:
    name: Build
    needs: create-release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: ["macos", "linux"]
        arch: ["arm64", "amd64"]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Test
        run: go test -v ./...
      - name: Build
        env:
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.arch }}
          REF: ${{ github.sha }}
        run: "./.github/workflows/build.sh"
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${GITHUB_REF#refs/tags/}" build/cftest-${{matrix.os}}-${{matrix.arch}}-${{github.sha}}.tgz
