name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --repo ${{ github.repository }} "${{github.ref_name}}"
  build:
    name: Build
    needs: create-release
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os: ["macos", "linux"]
        arch: ["arm64", "amd64"]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.25.0"
      - name: Test
        run: go test -v ./...
      - name: Build
        env:
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.arch }}
          REF: ${{ github.ref_name }}
        run: "./.github/workflows/build.sh"
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{github.ref_name}}" build/cftest-${{matrix.os}}-${{matrix.arch}}-${{github.ref_name}}.tgz
